server:
  port: 8888
##rabbitmq
spring:
  datasource:
    url: jdbc:mysql://192.168.0.132:3980/springbootdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid的配置
    initialSize: 5
    minIdle: 5
    maxActive: 10
    maxWait: 60000 # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 'x' # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      concurrency: 5
      max-concurrency: 10
      prefetch: 5



# 基础测试队列
basic_info_mq_exchange_name: basic_exchange
basic_info_mq_routing_key_name: basic_routing_key
basic_info_mq_queue_name: basic_queue
# 正常订单队列
user_order_exchange_name: user_order_exchange
user_order_routing_key_name: user_order_routing_key
user_order_queue_name: user_order_queue
# 订单超时后的队列
user_order_dead_exchange_name: user_order_dead_exchange
user_order_dead_routing_key_name: user_order_dead_routing_key
user_order_dead_queue_name: user_order_dead_queue